---
driver:
  name: docker_cli

transport:
  name: docker_cli

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_chef_for_busser: false
  require_ruby_for_busser: false
  requirements_path: test/integration/requirements.yml
  ansible_verbose: false
  ansible_verbosity: :warn
  ansible_version: latest
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  group_vars_path: test/integration/group_vars
  ignore_paths_from_root:
    - .bundle
    - .kitchen
    - .git
    - tests
    - vendor
  idempotency_test: true

platforms:
  - name: centos-6
    driver_config:
      platform: centos
      dockerfile: docker/centos-6.docker.erb
      privileged: true
      command: /sbin/init
  - name: centos-7
    driver_config:
      platform: centos
      dockerfile: docker/centos-7.docker.erb
      privileged: true
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      command: /sbin/init
  - name: debian-8
    driver_config:
      platform: debian
      dockerfile: docker/debian-8.docker.erb
      privileged: true
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      command: /sbin/init
  - name: ubuntu-12.04
    driver_config:
      platform: ubuntu
      dockerfile: docker/ubuntu-1204.docker.erb
      privileged: true
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      command: /sbin/init
  - name: ubuntu-14.04
    driver_config:
      platform: ubuntu
      dockerfile: docker/ubuntu-1404.docker.erb
      privileged: true
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      command: /sbin/init
  - name: ubuntu-16.04
    driver_config:
      platform: ubuntu
      dockerfile: docker/ubuntu-1604.docker.erb
      privileged: true
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      command: /sbin/init
  - name: fedora-25
    driver_config:
      platform: rhel
      dockerfile: docker/fedora-25.docker.erb
      privileged: true
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      command: /sbin/init

suites:
  - name: default
    verifier:
      default_path: test/integration/default/serverspec

verifier:
  name: serverspec
  remote_exec: false
  patterns:
    - '**/*_spec.rb'
