---
driver:
  name: docker
  require_chef_omnibus: false
  use_sudo: false

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_chef_for_busser: false
  require_ruby_for_busser: false
  requirements_path: test/integration/requirements.yml
  ansible_verbose: false
  ansible_verbosity: :warn
  ansible_version: latest
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  group_vars_path: test/integration/group_vars
  ignore_paths_from_root:
    - .bundle
    - tests
    - vendor
  idempotency_test: true

platforms:
  - name: centos-6
    driver_plugin: docker
    driver_config:
      platform: centos
      privileged: true
      dockerfile: docker/centos-6.docker.erb
      run_command: /sbin/init
  - name: centos-7
    driver_plugin: docker
    driver_config:
      platform: centos
      privileged: true
      volume:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      dockerfile: docker/centos-7.docker.erb
      run_command: /sbin/init
  - name: debian-8
    driver_config:
      platform: debian
      privileged: true
      volume:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      dockerfile: docker/debian-8.docker.erb
      run_command: /sbin/init
  - name: ubuntu-12.04
    driver_config:
      platform: ubuntu
      dockerfile: docker/ubuntu-1204.docker.erb
      privileged: true
      volume:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      run_command: /sbin/init
  - name: ubuntu-14.04
    driver_config:
      platform: ubuntu
      dockerfile: docker/ubuntu-1404.docker.erb
      privileged: true
      volume:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      run_command: /sbin/init
  - name: ubuntu-16.04
    driver_config:
      platform: ubuntu
      dockerfile: docker/ubuntu-1604.docker.erb
      privileged: true
      volume:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      run_command: /sbin/init
  - name: fedora-24
    driver_config:
      platform: rhel
      dockerfile: docker/fedora-24.docker.erb
      privileged: true
      volume:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      run_command: /sbin/init

suites:
  - name: default
    verifier:
      default_path: test/integration/default/serverspec

verifier:
  name: serverspec
  remote_exec: false
  patterns:
    - '**/*_spec.rb'
