-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 7539d8bd1a00a3c1bfd34cdb606d3a6372e83469
    hooks:
    -   id: trailing-whitespace
        files: \.(js|json|rb|md|py|sh|txt|yaml|yml)$
    -   id: check-yaml
    -   id: check-case-conflict
    -   id: check-json
    -   id: end-of-file-fixer
- repo: https://github.com/willthames/ansible-lint.git
  sha: v3.4.3
  hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$
      args: [--exclude=.travis.yml]
