---

- name: systemd daemon reload
  become: true
  systemd:
    daemon_reload: true
  when: java_rmiregistry_service_mgr == 'systemd'

- name: restart rmiregistry
  become: true
  become_user: root
  service:
    name: rmiregistry
    state: "{{ (java_rmiregistry_service_state != 'stopped') | ternary('restarted','stopped') }}"
    use: "{{ java_rmiregistry_service_mgr }}"
  when: java_rmiregistry_service_notify
