---

- name: systemd daemon reload
  become: yes
  command: /bin/systemctl daemon-reload
  when: java_rmiregistry_service_mgr == 'systemd'

- name: restart rmiregistry
  become: yes
  service:
    name: rmiregistry
    state: "{{ (java_rmiregistry_service_state != 'stopped') | ternary('restarted','stopped') }}"
  when: java_rmiregistry_service_notify
